apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cassandra
  name: cassandra
spec:
  ports:
  - port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: cassandra
status:
  loadBalancer: {}
