apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-core
  name: kafka-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-core
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-core
    spec:
      containers:
      - image: bitnami/kafka:3.6.1
        name: kafka
        resources: {}
        env: 
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_ZOOKEEPER_PROTOCOL
            value: PLAINTEXT
          - name: KAFKA_CFG_LISTENERS
            value: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka-core:9092,EXTERNAL://localhost:9094
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
status: {}
